server: &server
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 5432

production:
  <<: *server
  adapter: postgresql
  database: db/mystore
  pool: 5
  timeout: 5000
